#!/usr/bin/perl
$latex = 'platex %O %S';
$bibtex = 'pbibtex %O %B';
$dvipdf = 'dvipdfmx %O -o %D %S';
$pdf_mode = 3;
$pdf_previewer = 'okular --unique';
$clean_ext .= '%R.bbl %R.ltjruby %R.nav %R.snm %R.vrb';
